language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ekpo3/docker-react .

script:
  - docker run -e CI=true ekpo3/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-567933839930"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY